export { default as Home } from './home/Home'
export { default as Catalog } from './catalog/Catalog'
export { default as Cart } from './cart/Cart'
export { default as Item } from './item/Item'
export { default as Featured } from './featured/Featured'
export { default as Contact } from './contact/Contact'
export { default as About } from './about/About'
